name: Build Actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["5.10", "6.0"]
    steps:
      - uses: vapor/swiftly-action@afdde2275f2b916c2704383f3a6b72032adb488c
        with:
          toolchain: ${{ matrix.swift }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: swift test
        env:
          CI: 1
